name: donstestsite
favicon: null
layout_spectrum: 0.011235
typography_spectrum: 0
title: My testing page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A0A0A8'
    - '#984000'
    - '#484858'
    - '#D89008'
    - '#000000'
  brandStrength: 0.673221
  lightness: 0.343632
  saturation: 0.593632
  rhythmicContrast: 0.689138
purpose: []
