analytics: {}
color:
  brandColors:
    - '#A0A0A8'
    - '#984000'
    - '#484858'
    - '#D89008'
    - '#000000'
  brandStrength: 0.673221
  lightness: 0.343632
  rhythmicContrast: 0.689138
  saturation: 0.593632
cta: {}
layout_spectrum: 0.011235
name: donstestsite
opengraph: {}
purpose: []
typography_spectrum: 0
