name: donstestsite
favicon: null
layout_spectrum: 0.011235
typography_spectrum: 0
title: My testing page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1b1b3f'
    - '#d1d5e0'
    - '#a0a4af'
    - '#55576c'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.689138
purpose: []
